### ISSUE TITLE
[BE][REFACTOR] Team, Chat, ChatRoom 관련 인수 테스트

### ISSUE THREAD

**Issue by tigermint** [SWM-TEAM-SSH/dart-server#198]
## ✨ 목적
> 'A'를 하기위한 'B' 기능 추가(또는 기존 기능 확장), 연관된 issue or pr이 있을 경우 이곳에 `from #0` 같은 형태로 명시 
* 인수 테스트 작성
<br/>

### User
- Team (UsersTeamApiTest)
    - [x]  GET `/v1/users/me/teams/{teamId}`
    - [x]  DELETE `/v1/users/me/teams/{teamId}`
~~GET `/v1/users/me/teams` -> Deprecated~~
~~PATCH `/v1/users/me/teams/{teamId}` ->Deprecated~~
- Chatroom (UsersChatApiTest)
    - [x]  GET `/v1/users/me/chat/rooms`
    - [x]  GET `/v1/users/me/chat/rooms/{chatRoomId}`
### Team
- [x]  GET `/v1/teams`
- [x]  POST `/v1/teams`
- [x]  GET `/v1/teams/{id}`
- [x]  GET `/v1/teams/count`
### ChatRoom
- [x]  POST `/v1/chat/rooms`
### ChatMessage
- [x] MESSAGE `/app/chat/rooms/{chatRoomId}`
- [x]  GET `/v1/chat/rooms/{chatRoomId}/messages`
<br/>

## 📙 참고사항
- 스크린샷, 링크, 관련자료 등

<br/>

**Comment by chhs2131** [comment]
#202
